# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-04 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=6),
        ),
    ]
