# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 03:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0009_auto_20170208_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(default='Fake Name', max_length=40)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('special_key', models.CharField(blank=True, default='123456', max_length=6)),
                ('is_valid', models.BooleanField(default=False)),
                ('shoe_size', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(default='Not a real country', max_length=40)),
                ('birth_date', models.CharField(default='01/01/1111', max_length=15)),
                ('gender', models.CharField(default='N/A', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(default='Fake Name', max_length=40)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('special_key', models.CharField(blank=True, default='123456', max_length=6)),
                ('is_valid', models.BooleanField(default=False)),
                ('shoe_size', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(default='Not a real country', max_length=40)),
                ('birth_date', models.CharField(default='01/01/1111', max_length=15)),
                ('gender', models.CharField(default='N/A', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='special_key',
            field=models.CharField(blank=True, default='123456', max_length=6),
        ),
    ]
