# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-10 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0010_auto_20170209_0337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryAccount',
            new_name='OnlineAccount',
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
